### ISSUE TITLE
Seems there's a missing intervals-feedstock here:

### ISSUE THREAD

**Issue by mingwandroid** [conda-forge/sqlalchemy-utils-feedstock#8]
https://github.com/conda-forge/sqlalchemy-utils-feedstock/blob/3efafd4d19cd5a88a9cc67655b7d68e0b152ac06/recipe/meta.yaml#L33

**Comment by mingwandroid** [comment]
Pinging @jakirkham @pmlandwehr

**Comment by jakirkham** [comment]
I'm not a maintainer here. What is the ping for?

**Comment by mingwandroid** [comment]
@jakirkham you seem to get involved in most things, I thought you may care. Sorry.

**Comment by pmlandwehr** [comment]
I'm confused about the issue - the package is building just fine. How is this the case?

**Comment by mingwandroid** [comment]
It doesn't build fine if you exclude the defaults channel. `conda-forge` packages need to be standalone.

**Comment by pmlandwehr** [comment]
> `conda-forge` packages need to be standalone.

So, two points on this:
* Have the CIs been updated to reflect this more generally? Because that's a tenable requirement, but if so then the CIs should reflect it. If not, then it seems like a good advisory note but not a central requirement. (A best practice, but not a rule.) (Question answered: https://github.com/conda-forge/sqlalchemy-utils-feedstock/pull/7)
* This seems to have the potential to snowball into requests for me & other folks on  single-maintainer packages to create a few hundred new feedstocks for different dependent recipes. Getting all of these recipes into conda-forge is a great goal, but it seems like the right place for the requests is going to be the issue tracker over at conda-forge/staged-recipes, possibly with a link back to a reference issue at the feedstock with a missing dependency.

**Comment by pmlandwehr** [comment]
`intervals` has been added.
